name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ec2-user@ip-172-31-5-187:~/app

      - name: Run deployment script on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ip-172-31-5-187 << 'EOF'
          cd ~/app
          npm install
          npm start
          EOF
